{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failed():\n>       assert False\nE       assert False\n\ntests/test_simple/test_fail.py:2: AssertionError"}, "start": 1685185503779, "stop": 1685185503779, "uuid": "9f900eb7-2e3a-4d53-8d4c-4ee23613c1a2", "historyId": "448e521701035c3117ce177739c5f9b4", "testCaseId": "448e521701035c3117ce177739c5f9b4", "fullName": "tests.test_simple.test_fail#test_failed", "labels": [{"name": "parentSuite", "value": "tests.test_simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Lasha.local"}, {"name": "thread", "value": "57720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple.test_fail"}]}