{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail():\n>       assert False\nE       assert False\n\ntests/test_simple/test_fail.py:6: AssertionError"}, "start": 1685185503780, "stop": 1685185503780, "uuid": "471f9f13-09b6-45e2-bc0f-94cd5c8805bd", "historyId": "92af0fa1762daaa99602acea1e86e189", "testCaseId": "92af0fa1762daaa99602acea1e86e189", "fullName": "tests.test_simple.test_fail#test_fail", "labels": [{"name": "parentSuite", "value": "tests.test_simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Lasha.local"}, {"name": "thread", "value": "57720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple.test_fail"}]}