{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failed():\n>       assert False\nE       assert False\n\ntests/test_simple/test_fail.py:2: AssertionError"}, "start": 1685201585230, "stop": 1685201585230, "uuid": "b8c0467e-e877-40a9-a20c-fb22aa335115", "historyId": "448e521701035c3117ce177739c5f9b4", "testCaseId": "448e521701035c3117ce177739c5f9b4", "fullName": "tests.test_simple.test_fail#test_failed", "labels": [{"name": "parentSuite", "value": "tests.test_simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Lasha.local"}, {"name": "thread", "value": "75677-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple.test_fail"}]}