{"uuid": "b2519693-5a53-42a8-8d5c-cb03d7972e92", "children": ["c6d68c8e-20ef-440a-aeba-2b494ca9a8e5", "fae6a274-7a54-4bd5-a0a7-7edf43dc5c89", "60f86418-73e1-4eb8-9913-8de85c30a98d", "57cc8955-9fd6-4568-8fd7-195ad42e9aa1", "c3531098-b2d4-43be-8bff-e7671c74d997", "9b9ef065-0559-4a65-894c-185dd656a96d", "cdc646f6-4e39-4457-89aa-dbd91abff574"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\n\n", "trace": "  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/conftest.py\", line 42, in setup_browser\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lasha/PycharmProjects/Jenkins_Lasha/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 209, in check_response\n    raise exception_class(value)\n"}, "start": 1685201430893, "stop": 1685201491131}], "start": 1685201430893, "stop": 1685201491269}